server:
  port: 8085
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.66.75
    #    port: 5672
    virtual-host: /leyou
    username: leyou
    password: 22222222
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5